name = "iiti-pack"
author = "iiti"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04440fb795b3021e067439594b2b26c8b83b897de21d9db8ad88ee9b515335f7"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
