name = "iiti-pack"
author = "iiti"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9196b538333c30f2d505cbaf403d48d5c91d167466b0b2b1de08be006a637565"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
