name = "iiti-pack"
author = "iiti"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18ea3412eeb82b3fe8723ec13dd8a88d29eeb2dfd55d8aea6eac4716b0170da4"

[versions]
forge = "43.2.11"
minecraft = "1.19.2"
